
###
POST http://localhost:9000/api/clients
Content-Type: application/json

{
 "nom": "AAA",
 "prenom": "aaa"
}

###
GET http://localhost:9000/api/clients/1

###
GET http://localhost:9000/api/clients/1/comptes

###
POST http://localhost:9000/api/clients/2/comptes
Content-Type: application/json

{
   "solde" : 1000
}

###
GET http://localhost:9000/api/comptes/1

###
GET http://localhost:9000/api/clients/2

###
POST http://localhost:9000/api/clients
Content-Type: application/json

{ "nom" : "Durand", "prenom" : "Marcel" }

###
POST http://localhost:9000/api/clients/1/comptes
Content-Type: application/json

{ "solde" : 10000 }

###
GET http://localhost:9000/api/clients/1/comptes

###
GET http://localhost:9000/api/comptes/1

###
GET http://localhost:9000/api/comptes/2/operations

###
POST http://localhost:9000/api/comptes/2/operations
Content-Type: application/json

{ "valeur" : 100, "operationType" : "CREDIT" }

###
POST http://localhost:9000/api/comptes/2/operations
Content-Type: application/json

{ "valeur" : 100, "operationType" : "DEBIT" }

###
POST http://localhost:9000/api/comptes/1/operations/virements
Content-Type: application/json

{ "valeur" : 100, "idCompteDestinataire" : 3 }

###
DELETE http://localhost:9000/api/comptes/2

###generate project test
###
GET http://localhost:9000/api/infrastructuresportive/{{id}}/epreuve

###
POST http://localhost:9000/api/epreuve
Content-Type: application/json

###
POST http://localhost:9000/api/infrastructuresportive
Content-Type: application/json
{
    "id": 1,
    "nom": "Test",
    "adresse": "test",
    "capacite": 100,
    "epreuveList": null
}

###
POST http://localhost:9000/api/infrastructuresportive/1
{
  "nomEpreuve": "Epreuve 1",
  "dateEpreuve": "2024-06-06T14:45:30.000+0000",
  "infrastructureAccueil":
{
    "id": 1,
    "nom": "Test",
    "adresse": "test",
    "capacite": 100,
    "epreuveList": null
  },
  "nbPlacesDispo": 35
}

###
POST http://localhost:9000/api/epreu
Content-Type: application/jsonve

###
GET http://localhost:9000/api/infrastructuresportive/{{id}}/epreuve
